/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;

/**
 *
 * @author jules
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
    }
    
    private Dimension tailleEcranAdapté(){
        //get local graphics environment
        GraphicsEnvironment graphicsEnvironment =GraphicsEnvironment.getLocalGraphicsEnvironment();
        //get maximum window bounds
        Rectangle rectangle =graphicsEnvironment.getMaximumWindowBounds();
        //Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dim = new Dimension((int)rectangle.getWidth(),(int)rectangle.getHeight());
        return dim;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conteneur_central = new javax.swing.JPanel();
        Mot_de_passe = new javax.swing.JLabel();
        Bouton_creation_compte = new javax.swing.JButton();
        Bouton_connexion = new javax.swing.JButton();
        Nom_utilisateur = new javax.swing.JLabel();
        Entree_Nom_Utilisateur = new javax.swing.JTextField();
        Bouton_mdp_oublié = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(tailleEcranAdapté());

        Conteneur_central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Mot_de_passe.setText("Mot de passe");
        Conteneur_central.add(Mot_de_passe, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        Bouton_creation_compte.setText("Créer un compte");
        Bouton_creation_compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_creation_compteActionPerformed(evt);
            }
        });
        Conteneur_central.add(Bouton_creation_compte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 120, 40));

        Bouton_connexion.setText("Connexion");
        Bouton_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_connexionActionPerformed(evt);
            }
        });
        Conteneur_central.add(Bouton_connexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 120, 40));

        Nom_utilisateur.setText("Nom d'utilisateur");
        Conteneur_central.add(Nom_utilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        Entree_Nom_Utilisateur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Entree_Nom_Utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entree_Nom_UtilisateurActionPerformed(evt);
            }
        });
        Conteneur_central.add(Entree_Nom_Utilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 209, -1));

        Bouton_mdp_oublié.setText("Mot de passe oublié");
        Bouton_mdp_oublié.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_mdp_oubliéActionPerformed(evt);
            }
        });
        Conteneur_central.add(Bouton_mdp_oublié, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, -1));

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Conteneur_central.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(Conteneur_central, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(Conteneur_central, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Entree_Nom_UtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entree_Nom_UtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entree_Nom_UtilisateurActionPerformed

    private void Bouton_creation_compteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_creation_compteActionPerformed
        new Creation_compte().setVisible(true); // lien vers nouvelle fenetre
        this.dispose();
    }//GEN-LAST:event_Bouton_creation_compteActionPerformed

    private void Bouton_mdp_oubliéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_mdp_oubliéActionPerformed
        new Mdp_Oublie().setVisible(true); // lien vers nouvelle fenetre
        this.dispose();
    }//GEN-LAST:event_Bouton_mdp_oubliéActionPerformed

    private void Bouton_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_connexionActionPerformed
        new Acceuil_Client().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Bouton_connexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_connexion;
    private javax.swing.JButton Bouton_creation_compte;
    private javax.swing.JButton Bouton_mdp_oublié;
    private javax.swing.JPanel Conteneur_central;
    private javax.swing.JTextField Entree_Nom_Utilisateur;
    private javax.swing.JLabel Mot_de_passe;
    private javax.swing.JLabel Nom_utilisateur;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
