/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import base_de_donnees.Commubdd;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jules
 */
public class Creation_compte extends javax.swing.JFrame {
    String username;
    String password;
    String password_verif;
    String mail;
    String nom;
    String prenom;
    String categorie;
    Commubdd bdd = new Commubdd();
    /**
     * Creates new form Creation_compte
     */
    public Creation_compte() {
        initComponents();
        username = "";
        password = "";
        password_verif = "";
    }
    private Dimension tailleEcranAdapté(){
        //get local graphics environment
        GraphicsEnvironment graphicsEnvironment =GraphicsEnvironment.getLocalGraphicsEnvironment();
        //get maximum window bounds
        Rectangle rectangle =graphicsEnvironment.getMaximumWindowBounds();
        //Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dim = new Dimension((int)rectangle.getWidth(),(int)rectangle.getHeight());
        return dim;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nom_utilisateur = new javax.swing.JLabel();
        Nom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Entree_mail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Retour = new javax.swing.JButton();
        Entree_mdp_verification = new javax.swing.JPasswordField();
        Entree_mdp = new javax.swing.JPasswordField();
        Entree_nom_utilisateur = new javax.swing.JTextField();
        Prenom = new javax.swing.JTextField();
        Nom_utilisateur1 = new javax.swing.JLabel();
        Nom_utilisateur2 = new javax.swing.JLabel();
        Categorie = new javax.swing.JComboBox<>();
        Nom_utilisateur3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(tailleEcranAdapté());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nom_utilisateur.setText("Categorie :");
        jPanel1.add(Nom_utilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 90, 20));

        Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomActionPerformed(evt);
            }
        });
        jPanel1.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 240, -1));

        jLabel1.setText("Mot de passe :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setText("Réécrire le mot de passe :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel3.setText("Adresse mail :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        Entree_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entree_mailActionPerformed(evt);
            }
        });
        jPanel1.add(Entree_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 240, -1));

        jButton1.setText("Création du compte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 180, 50));

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        jPanel1.add(Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Entree_mdp_verification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entree_mdp_verificationActionPerformed(evt);
            }
        });
        jPanel1.add(Entree_mdp_verification, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, -1));

        Entree_mdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entree_mdpActionPerformed(evt);
            }
        });
        jPanel1.add(Entree_mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 240, -1));

        Entree_nom_utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entree_nom_utilisateurActionPerformed(evt);
            }
        });
        jPanel1.add(Entree_nom_utilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, -1));

        Prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomActionPerformed(evt);
            }
        });
        jPanel1.add(Prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 240, -1));

        Nom_utilisateur1.setText("Nom utilisateur :");
        jPanel1.add(Nom_utilisateur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));

        Nom_utilisateur2.setText("Prenom :");
        jPanel1.add(Nom_utilisateur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 90, 20));

        Categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Professeur", "Service technique" }));
        Categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorieActionPerformed(evt);
            }
        });
        jPanel1.add(Categorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 240, -1));

        Nom_utilisateur3.setText("Nom :");
        jPanel1.add(Nom_utilisateur3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomActionPerformed
        username = Nom.getText();
    }//GEN-LAST:event_NomActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        try {
            new Authentification().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Creation_compte.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose(); // fermeture de la fenetre
    }//GEN-LAST:event_RetourActionPerformed

    private void resetEntrer(){
        mail = "";
        password = "";
        password_verif = "";
        nom = "";
        prenom = "";
        username = "";
        categorie = "";
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetEntrer();
        mail = Entree_mail.getText();
        char mdp[] = Entree_mdp.getPassword();
        for (char c : mdp)
            password+=c;
        mdp = Entree_mdp_verification.getPassword();
        for (char c : mdp)
            password_verif+=c;
        username = Entree_nom_utilisateur.getText();
        if(! password.equals(password_verif)){
            Entree_mdp.setText("");
            Entree_mdp_verification.setText("");
            new Affichage_erreur("Les mots de passe ne sont pas identiques").setVisible(true);
        }else{
            mail = Entree_mail.getText();
            prenom = Prenom.getText();
            nom = Nom.getText();
            categorie = Categorie.getToolTipText();
            try {
                bdd.creationUtilisateur(nom, prenom, username, password, mail, categorie);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Creation_compte.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
            new Authentification().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Creation_compte.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Entree_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entree_mailActionPerformed
        mail = Entree_mail.getText();
    }//GEN-LAST:event_Entree_mailActionPerformed

    private void Entree_mdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entree_mdpActionPerformed
        char mdp[] = Entree_mdp.getPassword();
        for (char c : mdp)
            password += c;
    }//GEN-LAST:event_Entree_mdpActionPerformed

    private void Entree_mdp_verificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entree_mdp_verificationActionPerformed
        char mdp[] = Entree_mdp.getPassword();
        for (char c : mdp)
            password_verif +=c;
    }//GEN-LAST:event_Entree_mdp_verificationActionPerformed

    private void Entree_nom_utilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entree_nom_utilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entree_nom_utilisateurActionPerformed

    private void PrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomActionPerformed

    private void CategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategorieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creation_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creation_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creation_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creation_compte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creation_compte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Categorie;
    private javax.swing.JTextField Entree_mail;
    private javax.swing.JPasswordField Entree_mdp;
    private javax.swing.JPasswordField Entree_mdp_verification;
    private javax.swing.JTextField Entree_nom_utilisateur;
    private javax.swing.JTextField Nom;
    private javax.swing.JLabel Nom_utilisateur;
    private javax.swing.JLabel Nom_utilisateur1;
    private javax.swing.JLabel Nom_utilisateur2;
    private javax.swing.JLabel Nom_utilisateur3;
    private javax.swing.JTextField Prenom;
    private javax.swing.JButton Retour;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
