/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import base_de_donnees.Commubdd;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import objet.Utilisateur;

/**
 *
 * @author Ash
 */
public class Liste_groupe extends javax.swing.JFrame {

    public Liste_groupe() {
        initComponents();
        affichageArbreGroupe();
    }
    
    private void affichageArbreGroupe(){
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("root");
        DefaultMutableTreeNode professeur = new DefaultMutableTreeNode("Professeur");
        DefaultMutableTreeNode etudiant = new DefaultMutableTreeNode("Etudiant");
        DefaultMutableTreeNode service_Technique = new DefaultMutableTreeNode("Service technique");
        DefaultMutableTreeNode administrateur = new DefaultMutableTreeNode("Administrateur");
        root.add(etudiant);
        root.add(professeur);
        root.add(service_Technique);
        root.add(administrateur);
        Commubdd commubdd = new Commubdd();
        boolean pasDeFeuille = true;
        DefaultMutableTreeNode feuilleCourante; // = TDA(x)
        try {
            List<String> listGrp = commubdd.getListGrp("etude");
            for(String nomGroupe : listGrp){
                etudiant.add(new DefaultMutableTreeNode(nomGroupe));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Acceuil_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            List<String> listGrp = commubdd.getListGrp("technique");
            listGrp.forEach((nom) -> {
                service_Technique.add(new DefaultMutableTreeNode(nom));
            });
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Acceuil_Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        JTree arbre_groupes= new JTree(root); 
        Conteneur_liste.add(arbre_groupes);
        arbre_groupes.setRootVisible(true);
        arbre_groupes.setShowsRootHandles(true);
        Conteneur_liste.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conteneur_liste = new javax.swing.JPanel();
        Bouton_retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Conteneur_liste.setBackground(new java.awt.Color(153, 255, 153));
        Conteneur_liste.setLayout(new java.awt.BorderLayout());

        Bouton_retour.setText("Retour");
        Bouton_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(472, Short.MAX_VALUE)
                .addComponent(Conteneur_liste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bouton_retour)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bouton_retour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(Conteneur_liste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        Conteneur_liste.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_retourActionPerformed
        this.dispose();
    }//GEN-LAST:event_Bouton_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste_groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste_groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste_groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste_groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Liste_groupe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_retour;
    private javax.swing.JPanel Conteneur_liste;
    // End of variables declaration//GEN-END:variables
}
